// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PollaMundialista.Infrastructure.Persistence;

#nullable disable

namespace PollaMundialista.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PollaMundialista.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("KickoffAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e32723a0-f845-5e32-2acd-b4006d87b053"),
                            AwayTeam = "Brasil",
                            Group = "A",
                            HomeTeam = "Argentina",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 5, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("47d0761e-3a4a-5429-f7e1-d60ca7d6494b"),
                            AwayTeam = "Portugal",
                            Group = "B",
                            HomeTeam = "Alemania",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 5, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bcde8fa0-b37a-0d9c-f759-77641a3c8332"),
                            AwayTeam = "Francia",
                            Group = "A",
                            HomeTeam = "España",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 6, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ad7b296e-4660-d254-15bf-cf99993f2a4a"),
                            AwayTeam = "Países Bajos",
                            Group = "B",
                            HomeTeam = "Inglaterra",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 6, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d3b7c04-e290-aebc-b98c-07022c34e334"),
                            AwayTeam = "España",
                            Group = "A",
                            HomeTeam = "Argentina",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 9, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9807967c-d6a0-adb7-1091-0d7275ea77a4"),
                            AwayTeam = "Inglaterra",
                            Group = "B",
                            HomeTeam = "Alemania",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 9, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e6c273b0-b176-f6c0-6882-8090996f1891"),
                            AwayTeam = "Francia",
                            Group = "A",
                            HomeTeam = "Brasil",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 10, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("ab388da8-53a5-1c25-b7ab-00e8b6deb9e2"),
                            AwayTeam = "Países Bajos",
                            Group = "B",
                            HomeTeam = "Portugal",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 10, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("cddf495c-7384-f230-1152-e0d690061d0f"),
                            AwayTeam = "Argentina",
                            Group = "A",
                            HomeTeam = "Francia",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 13, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("66690444-625a-d208-23a3-a968fc127a83"),
                            AwayTeam = "Alemania",
                            Group = "B",
                            HomeTeam = "Países Bajos",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 13, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c731b970-5dd4-9e19-9738-fecca2baf32c"),
                            AwayTeam = "España",
                            Group = "A",
                            HomeTeam = "Brasil",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 14, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5f206830-7950-e02c-c808-b5fbf450fc51"),
                            AwayTeam = "Portugal",
                            Group = "B",
                            HomeTeam = "Inglaterra",
                            KickoffAt = new DateTimeOffset(new DateTime(2026, 12, 14, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PollaMundialista.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("PollaMundialista.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PollaMundialista.Domain.Entities.Match", b =>
                {
                    b.OwnsOne("PollaMundialista.Domain.ValueObjects.MatchResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AwayScore")
                                .HasColumnType("integer")
                                .HasColumnName("AwayScore");

                            b1.Property<int>("HomeScore")
                                .HasColumnType("integer")
                                .HasColumnName("HomeScore");

                            b1.HasKey("MatchId");

                            b1.ToTable("MatchResults", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("PollaMundialista.Domain.Entities.Prediction", b =>
                {
                    b.OwnsOne("PollaMundialista.Domain.ValueObjects.MatchResult", "PredictedResult", b1 =>
                        {
                            b1.Property<Guid>("PredictionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AwayScore")
                                .HasColumnType("integer")
                                .HasColumnName("PredictedAwayScore");

                            b1.Property<int>("HomeScore")
                                .HasColumnType("integer")
                                .HasColumnName("PredictedHomeScore");

                            b1.HasKey("PredictionId");

                            b1.ToTable("Predictions");

                            b1.WithOwner()
                                .HasForeignKey("PredictionId");
                        });

                    b.Navigation("PredictedResult")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
